spring.application.name=ResumeBuilder

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

#Email Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${MAIL_FROM}

spring.mail.properties.mail.debug=true



#Application info
app.base.url=http://localhost:8080

#Cloudinary info
cloudinary.cloud-name=dw50jwijz
cloudinary.api-key=764487955683669
cloudinary.api-secret=L9DNW6n-8-O8Lfd_P5AEM_bosNk

#Jwt configuration
jwt.secret=your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key
jwt.expiration=604800000

management.endpoint.health.show-details=always
#management.health.mail.enabled=false
